USE codeup_test_db;
TRUNCATE albums;
INSERT INTO albums (artist, name, release_date, sales, genre)
VALUES ('Michael Jackson','Thriller',1982,47.3,'Pop, post-disco, funk, rock'),
       ('AC/DC','Back in Black',1980,29.4,'Hard rock'),
       ('Meat Loaf','Bat Out of Hell',1977,21.7,'Hard rock, glam rock, progressive rock'),
       ('Pink Floyd','The Dark Side of the Moon',1973,24.4,'Progressive rock'),
       ('Whitney Houston / Various artists','The Bodyguard',1992,28.4,'R&B, soul, pop, soundtrack'),
       ('Eagles','Their Greatest Hits (1971–1975)',1976,41.2,'Country rock, soft rock, folk rock'),
       ('Bee Gees / Various artists','Saturday Night Fever',1977,21.6,'Disco'),
       ('Fleetwood Mac','Rumours',1977,27.9,'Soft rock'),
       ('Shania Twain','Come On Over',1997,29.6,'Country, pop'),
       ('Led Zeppelin','Led Zeppelin IV',1971,29,'Hard rock, heavy metal, folk rock'),
       ('Michael Jackson','Bad',1987,22.2,'Pop, rhythm and blues, funk and rock'),
       ('Alanis Morissette','Jagged Little Pill',1995,24.4,'Alternative rock'),
       ('Michael Jackson','Dangerous',1991,17,'New jack swing, R&B and pop'),
       ('Celine Dion','Falling into You',1996,21.2,'Pop, soft rock'),
       ('Eagles','Hotel California',1976,31.5,'Soft rock'),
       ('The Beatles','Sgt. Pepper''s Lonely Hearts Club Band',1967,18.2,'Rock'),
       ('Various artists','Dirty Dancing',1987,17.9,'Pop, rock, R&B'),
       ('Adele','21',2011,30.8,'Pop, soul'),
       ('Madonna','The Immaculate Collection',1990,19.4,'Pop, dance'),
       ('Celine Dion','Let''s Talk About Love',1997,19.3,'Pop, soft rock'),
       ('Metallica','Metallica',1991,25.2,'Heavy metal'),
       ('The Beatles','1',2000,23.4,'Rock'),
       ('The Beatles','Abbey Road',1969,14.4,'Rock'),
       ('ABBA','Gold: Greatest Hits',1992,23,'Pop, disco'),
       ('Bruce Springsteen','Born in the U.S.A.',1984,19.6,'Heartland rock'),
       ('Pink Floyd','The Wall',1979,18.7,'Progressive rock'),
       ('James Horner','Titanic: Music from the Motion Picture',1997,18.1,'Film score'),
       ('Dire Straits','Brothers in Arms',1985,17.7,'Roots rock, blues rock, soft rock'),
       ('Nirvana','Nevermind',1991,16.7,'Grunge, alternative rock'),
       ('Santana','Supernatural',1999,20.5,'Latin rock'),
       ('Guns N'' Roses','Appetite for Destruction',1987,21.9,'Hard rock'),
       ('Elton John','Goodbye Yellow Brick Road',1973,8.5,'rock, pop rock, glam rock');

